### ISSUE TITLE
writing up model theory

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/syntax-and-semantics-of-abts#15]
- [x] Σ-monoids
- [x] the signature endofunctor `\mathcal{F}_\Sigma(-)`
- [x] Σ-models are sigma monoids `A` equipped with an initial algebra `mathcal{F}_\Sigma(A) \to A`
- [x] interpretation of terms into a Σ-model

Basically, this will involve something between the stuff in the unisorted papers and the polymorphic paper; we won't need all the complexity of the latter, but a bit of the machinery presented there will be useful.

We'll have to adjust this slightly to deal with symbols. I think this basically means a bit more indexing, and "targeting" the substitution structure such that it pretty much ignores symbols. It might get a little bit icky, not sure.

**Comment by jonsterling** [comment]
@freebroccolo By the way, just to be clear, the tensor operation on those presheafs is indeed the day convolution, right?

**Comment by freebroccolo** [comment]
Yes. In some cases there are a few alternate ways of describing it. I think that monoids paper from Maro describes a couple of them. The coend paper probably mentions it too.

**Comment by freebroccolo** [comment]
Sorry for the confusion. I should have double checked. But anyway, on page 481 in [this paper](http://www.tac.mta.ca/tac/volumes/27/18/27-18.pdf) he describes the Day convolution alongside this substitution monoidal structure. I guess the substitution version goes back to Kelly and Joyal, and is discussed quite a bit in the species literature.
