### ISSUE TITLE
consider developing a theory of refinements

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/syntax-and-semantics-of-abts#21]
The current refinement example is kind of "ad hoc"; it may make sense to develop a full theory of refinements in the style of PFPL/2 Chapter 25. Then, the case study would not have to introduce any new machinery, but could be an example of applying the refinements kit.

**Comment by freebroccolo** [comment]
This might be interesting. If we were to develop a "full theory", do you think it might make sense to include some of the Melliès/Zeilberger material as part of the model theory?

**Comment by jonsterling** [comment]
That'd be pretty cool... Do you think that we would actually have to change the model theory for the "structural" framework?

**Comment by jonsterling** [comment]
So, here's kind of what I was thinking... A refinement `φ refines s` in a model `A` shall be a PER on the closed terms of sort `s` in `A`, indexed by a symbol context; then, there's a functor from these `SCtx`-indexed PERs to sequent-indexed PERs, which is given by the usual logical relations-style explanation of hypothetico-general judgment; from this, for any refinement `φ` we can interpret the satisfaction judgment `Y || Γ != M = N \in φ`. We'd require that there is a forgetful functor that relates reflexive terms in refinement to well-sorted terms, and show that this commutes with the functor that extends the relations to open terms.

This lets us define a behavioral type system over abstract binding trees....

Does this sound plausible? I'm not quite sure how to talk about these "indexed PERs" categorically, but it seems like we should be able to figure that bit out.

**Comment by jonsterling** [comment]
^^^ By the way, in the above satisfaction judgment, I meant `Y,Γ` to be "refined" contexts (that is, instead of sorts, there are refinements). So it would be kind of like what I proposed above, but a little bit more intricate.

I think that developing this would actually be a pretty interesting / novel contribution, since it would essentially be the generalization of Nuprl-style type theory that I've been wanting for a long time to a many-sorted framework.
