### ISSUE TITLE
Notation

### ISSUE THREAD

**Issue by freebroccolo** [jonsterling/syntax-and-semantics-of-abts#28]
I'm creating this issue just to collect some thoughts I have about notation both for the paper and the implementation.

**Comment by freebroccolo** [comment]
#### Comma

One thing that has always bugged me about the the Fiore and Hamana papers is the notation they use for the comma construction. Perhaps it follows practice in the literature (I don't really know) but I find it unclear and confusing to leave the functors out and not make it explicit when the identity and constant functors are being used. I suppose it might be okay if it was explained once when the notation is first used. I think there is one Hamana paper where he mentions that they would write it differently if "being rigorous" but then doesn't explain what he means…

Anyway, in agda we can write comma like this:

```agda
record _↓[_]_ {𝒞 𝒟 𝒱 : Set} (F : 𝒞 → 𝒱) (𝒱[_,_] : 𝒱 → 𝒱 → Set) (G : 𝒟 → 𝒱) : Set where
  no-eta-equality
  constructor ∃⟨_,_⟩↓_
  field
    dom : 𝒞
    cod : 𝒟
    map : 𝒱[ F dom , G cod ]
```

and then derive slice:

```agda
_/_ : {𝒞 : Set} (𝒞[_,_] : 𝒞 → 𝒞 → Set) (I : 𝒞) → Set
𝒞[_,_] / I = ∏.idn ↓[ 𝒞[_,_] ] ∏.! I
```

So for example, the universe of discourse for polymorphic syntax would look something like this:

```agda
𝔊 : Set
𝔊 = ∐.[ Nat.t ∋ n ] dom ↓[ SET[_,_] ] ∏.! (𝒯 n) ⊗.t 𝒯 n

𝔘 : Set
𝔘 = 𝔓 𝔊
```

**Comment by jonsterling** [comment]
I found the comma thing super confusing too. Took me a half hour to figure out what the hell was going on!

**Comment by freebroccolo** [comment]
If we decide to keep that notation in the paper I think we should definitely explain it in a footnote at the very least.

**Comment by jonsterling** [comment]
If you want to make it explicit-by-default in the paper, I'd be in favor; we could put a footnote relating it to the stupid notation.

**Comment by freebroccolo** [comment]
Okay. By the way, are you still in favor of using the hat notation for presheaves? I noticed that the script P is at mentioned in Mac Lane and Moerdijk. It looks like in several of the Fiore / Hamana papers they just use exponential style.

The main reason I was thinking about it is that I started reading through Taylor again and he has an interesting hat notation he uses for variables and weakening (see pages 10 and 440). Might be nice to adopt his conventions there though it might be confusing if we also use hat for presheaves. He expands on it throughout the book, incorporating it with the adjoint star notation, etc.

**Comment by jonsterling** [comment]
Oh interesting... Where is that in Mac Lane / Moerdijk?

I don't feel *too* strongly about the hat notation, but it is very standard; and I think the script-P notation might be a bit too unfamiliar to most people; I'd be OK with using the exponential style though, if we want to save the hat for weakening as in Taylor.

**Comment by freebroccolo** [comment]
Hmm, maybe it's not quite what I thougth in Mac Lane / Moerdijk. It is at least mentioned on page 57 although he describes it in terms of boolean algebras (for no particularly good reason).I thought I saw it other times in there but maybe I was looking at a different book.

Another option would be to just use `PSh` but I think in the end the exponential style is probably ideal for a number of technical reasons so I'd be happy with that.

**Comment by jonsterling** [comment]
OK, cool; let's use the exponential style; well, it's even more economical for covariant presheaves anyway, so that's another point in favor of it.

**Comment by freebroccolo** [comment]
On the comma category thing: maybe we should just remove the Grothendieck construction part and replace it with a brief overview of comma in general and show how that specializes to the cases used in the paper (including the Grothendieck construction).

**Comment by jonsterling** [comment]
Sure, I think that sounds like a reasonable idea. Would you like to take that on?

**Comment by freebroccolo** [comment]
Yeah I can do that.

**Comment by jonsterling** [comment]
I've added a bit in the paper that explains that weird notation for the comma construction, making specific the functors involved.
