### ISSUE TITLE
rendering problems?

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/syntax-and-semantics-of-abts#32]
@freebroccolo Bob downloaded this and when he tried to view the PDF on his Mac in Skim, he said it rendered all weird and looked like it had runes in it. Is it possible that this could be cause either by the fonts or lualatex?

**Comment by freebroccolo** [comment]
Not sure what could be causing that.

I suppose it is possible there's something bad going on with how the document is being generated but I would be a bit surprised. It seems to render okay with Skim on two machines that I have tried and I also able to view the document from mobile safari.

As far as I understand, all of the necessary font stuff should be embedded in the document.

We could try rendering it with just pdflatex and basic fonts if you want. In any case, it seems more likely that somehow the document got corrupted when he tried to download it or that something else was going on.

**Comment by jonsterling** [comment]
Yeah, it's really weird... I too suspect that something just got corrupted about the download, but I'm not sure. It's worked fine for me on every device I've tried to view it in.

I like the nice typographic stuff that we're able to have with the current setup, but I too wonder if we ought to try using "vanilla" fonts and pdflatex—if only to reduce the number of variables in play when we send it to someone. I don't actually think that these are the problem (it's probably just a corrupted download), but on the other hand, it's probably not a good idea for me to waste a bunch of bob's time trying to make sure that's the case :). Also, it's probably likely that if we submit this somewhere, there will be a "house style" anyway (depending on the venue, we may also have to turn off colors too in that case, but I find them useful at least while drafting).

**Comment by freebroccolo** [comment]
I don't mind switching back to pdflatex and disabling the unicode math stuff if you want to try it. However, one potentially significant drawback to doing that is we'll no longer be able to include agda snippets in a clean way (due to the unicode). I think we would need to use something like lhs2tex instead.

**Comment by jonsterling** [comment]
@freebroccolo Ah, that's unfortunate... I think maybe, at least for now, it might be worthwhile to go back to vanilla pdflatex, but we should revisit if we end up making a version of the paper where the Agda development is actually integrated. Does that sound OK?

**Comment by jonsterling** [comment]
Incidentally, now that I think of it, I have also noticed some strange font failures in the versions that of the PDF that come from your commits; for instance, `\mathsf` always renders as upright roman characters, for some reason.

**Comment by freebroccolo** [comment]
@jonsterling that's okay with me. On the font issues, do you know which commits you saw that with?

**Comment by jonsterling** [comment]
@freebroccolo I think it's that way on `master` right now

**Comment by jonsterling** [comment]
(If you look at the case study, all those operator names are `\mathsf`)

**Comment by freebroccolo** [comment]
Huh, that is weird. Not sure what's causing that. Anyway, I switched it back to pdflatex.

**Comment by freebroccolo** [comment]
By the way, you can try rendering it (with standard pdflatex stuff) using euler/palatino by uncommenting the two lines above the microtype section. I think it looks a lot nicer that way (I don't really like the default fonts) but I'll leave it up to you whether you want use them or not.

**Comment by jonsterling** [comment]
thanks; I think Euler and Palatino look nice. (Well, I like Euler for math better than Palatino for text, but they seem to go together quite nicely.)
