### ISSUE TITLE
Move macros for ABT judgments into a .sty file

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/syntax-and-semantics-of-abts#33]
This way we can share notation between papers (in particular, I'm thinking of "type refinements for the working class").

**Comment by freebroccolo** [comment]
Sounds like a good idea. If you intend to move it into a separate repo and use submodules, maybe we should do that for the agda code too.

**Comment by jonsterling** [comment]
Cool. Re submodules, that might be worthwhile.
