### ISSUE TITLE
free symbols & finite support? switch to sheaves!

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/syntax-and-semantics-of-abts#35]
What's the difference between our model and something like nominal sets? The latter have a notion of "finite support" which allows you to talk about which symbols are *actually* used in an expression; in our current framework, we might have an expression `M : Expr(V)` which is really just a degenerate / weakened / "puffed up" version of some expression `M' : Expr(U)`, but we have no way of knowing.

We have hand-waved about calculating the free symbols of an expression, expecting that it would be trivial, but I believe that we actually need this notion of finite support, along with a constraint that when we know the free symbols / support of an expression, we can always come up with a *unique* expression that lives in the world that contains *only* those free symbols.

So, if we have `ϱ : U --> V` and `M : Expr(V)`, we say that `U` supports `M` if `M` is invariant under all renamings that don't touch anything in `U`. Now, we want to impose an extra condition, which is that if `U` supports `M`, then, we can reach back and get a *unique* `M' : Expr(U)` such that `M'ϱ == M`. This condition ensures that the notion of finite support / free symbols is well-behaved—otherwise, it might be that we could lose information in the course of a renaming.

Now, the interesting thing is that the above condition is *exactly* the sheaf condition for functors `Set^I` where `I` is the category of finite cardinals and their injective maps. `Sh(I^op)` is, by the way, called the Schanuel topos.

Fiore & Staton have written about this here:
http://www.cs.ox.ac.uk/people/samuel.staton/papers/ic05.pdf

So, I think what we need to do is say that operators will be *sheaves* over symbol contexts with the atomic topology; we may also need to change the model theory so that the semantic universe is will be `Sh((SCtx * Ctx)^op)` instead of the presheaf category that we are currently using.

Free symbols of some term `M:Expr(V)` can be "calculated" by taking the least subset of `U` of `V` such that `M` is invariant under all renamings `V\U -> V`, or something along those lines.

I'm glad I took the time to read about this stuff; I was wondering what I'd been missing by not using nominal sets, and now I know. I guess Pitts has found the emphasis on permutations in the nominal sets presentation very helpful, but the equivalent presentation as objects of the Schanuel topos is *way* more clear to me.

@freebroccolo @jozefg Does this sound plausible?

**Comment by freebroccolo** [comment]
Hmm, this sounds very interesting. I'll have to do some reading before I have much to say. What you've said sounds reasonable though I think. I have seen mention of the Schanuel topos a few times recently but I don't remember where. Perhaps it was in something from Pitts since I don't remember that Fiore paper.

**Comment by freebroccolo** [comment]
By the way, it looks like there is an expanded thesis version [here](https://www.cl.cam.ac.uk/techreports/UCAM-CL-TR-688.pdf).

**Comment by jonsterling** [comment]
So, assuming that covariant sheaves on `I↓S` are indeed analogous to multi-sorted nominal sets (i.e. assuming that the proposal above actually works), then I think we can nicely present operator signatures as an arity-indexed family of covariant sheaves on `I↓S`. Consider the following operator signature:

```
Y, u : exp !!- get[u] : ()exp
Y, u : exp !!- set[u] : ({}[].exp)exp
Y !!- num[n] : ()exp  (n in Nat)
```

Now, let's define the sheaf `Sym[τ](Y) := { u in |Y| | Y(u) == τ }` or whatever; I believe this should be a sheaf, since this is a subset of the yoneda embedding of the empty symbol context, and all representable presheaves are sheaves under a subcanonical topology (such as the atomic topology). For two sheaves `F,G`, we'll write `F + G` for their coproduct and `F * G` for the product; we'll write `N` for the sheaf of natural numbers.

```
O[()exp] := { Sym[τ] + N }
O[({}[].exp)exp] := { Sym[t] }
```

Then, the operator `get[u]` is interpreted as `inl(u) : O[()exp](Y)` when `Y(u) == exp`, etc. I think that splitting this up so that the (pre)sheaf stuff happens only on the symbol contexts, and dealing with the arities through the family of (pre)sheaves makes a lot of stuff more clear; in the case of presheaves, it was equivalent, but for sheaves, it's probably not.

**Comment by freebroccolo** [comment]
This sounds really cool. Is this why you are formalizing the nominal sets stuff now?

**Comment by jonsterling** [comment]
Yeah, mostly I'd like to make sure I understand wtf's going on with this machinery

**Comment by jonsterling** [comment]
@freebroccolo 

I'm now fairly convinced that any such sheaf can be turned into an `s`-sorted nominal set (written `Nom[s]`) as defined by Pitts, for any "global" sort assignment `s : 𝔸 -> Sorts` (where `𝔸` is the infinite set of all atoms), by simply restricting our attention to the behavior of the sheaf at worlds whose sort assignments are restrictions of `s`. But it doesn't really make any sense to go the other direction—the crux of the problem is that a (pre)sheaf on symbol contexts must be defined over *all* symbol contexts, not just those whose sort assignments can be glued together in to a single assignment of sorts to all of `𝔸`.

Here's another way to think about it, though. Each of our sheaves gives rise to a *family* of multi-sorted nominal sets (indexed by sort assignments `s : 𝔸 -> Sorts`). So, we don't have an equivalence between `s`-sorted nominal sets and our sheaves, since our sheaves contain too much data; instead, we should pursue an equivalence between `Sh(I[S])` and *global sections* of `Nom[–]` (i.e. for each `s : 𝔸 -> Sorts`, an `s`-sorted nominal set).

**Comment by freebroccolo** [comment]
I think the way you describe this makes sense. It would be nice to try and figure out the details formally. I've started making some improvements to the groupoid library that should make it more usable for this (CwF and LCCC stuff) but it will probably be a few more days before it's ready.

**Comment by jonsterling** [comment]
Yes, that'd be excellent. I'd love to prove this supposed equivalence formally...

**Comment by freebroccolo** [comment]
By the way, how much of this machinery (also considering the refinement work) do you think actually requires a full topos theoretic treatment? Something that has been in the back of my mind but seems more relevant now is to what extent we can just consider CWA/CWF/LCCC/Hyperdoctrine structures or pretoposes more generally (specifically [ΠW-pretopos with multiple choice](http://ncatlab.org/nlab/show/predicative+topos)).

**Comment by jonsterling** [comment]
@freebroccolo In the ABT paper, we need at most a ΠW pretopos.

In the refinements paper, at least as-written, essential use is made of the subobject classifier (this is precisely what happens when you give a meaning explanation like "To know `J` is to know the meaning of some other judgment `J'`"). However, I believe that the refinements stuff could be developed in a predicative setting by using a stratified pseudo-topos (i.e. analogous, I think, to type theory with a predicative universe hierarchy).

**Comment by jonsterling** [comment]
From my perspective as an intuitionist, a category of (pre)sheaves does not give rise to a topos, only a pretopos; likewise, though the Schanuel topos is boolean in classical mathematics, I have a feeling that if developed in a constructive setting, it cannot be shown to be boolean.

I'm not really sure what the right thing is to do *in a paper*, though... I didn't want to distract from the main point of the development by saying things like "The Schanuel Pretopos", etc.; but on the other hand, in the refinements paper, the use of the subobject classifier may make it seem as though the construction is inherently impredicative (which it is not); it might be worthwhile to use the stratified pseudo-topos stuff in order to have a way to talk about "small judgments" and "large judgments", but I wasn't sure if it would be interesting, or just a distraction.

What do you think?

**Comment by freebroccolo** [comment]
Okay, that sounds reasonable I think. I haven't read much of the pretopos literature properly but from [this](http://www.phil.cmu.edu/projects/ast/Papers/van_den_Berg_sheaves.pdf) it sounds like there is a weaker notion than a stratified pseudotopos that might work. Specifically, he describes a ΠW pretopos satisfying a universe operator axiom that corresponds somehow to Palmgren's work on universe operators.

**Comment by freebroccolo** [comment]
> From my perspective as an intuitionist, a category of (pre)sheaves does not give rise to a topos, only a pretopos; likewise, though the Schanuel topos is boolean in classical mathematics, I have a feeling that if developed in a constructive setting, it cannot be shown to be boolean.

Yeah, I suspect this would be the case too.
 
> I'm not really sure what the right thing is to do in a paper, though... I didn't want to distract from the main point of the development by saying things like "The Schanuel Pretopos", etc.; but on the other hand, in the refinements paper, the use of the subobject classifier may make it seem as though the construction is inherently impredicative (which it is not); it might be worthwhile to use the stratified pseudo-topos stuff in order to have a way to talk about "small judgments" and "large judgments", but I wasn't sure if it would be interesting, or just a distraction.

Yeah, I'm not sure either. I agree that drawing attention to the fact that something is a pretopos instead of a topos might be unnecessarily obscure, particularly if nothing further is said about why that distinction is being made. However, I am also a little worried about the refinement stuff seeming inherently impredicative like you say.

There's the philosophical/foundational aspect to consider but at this point I suppose I am more concerned just with what it would mean to implement this practically in a predicative type-theoretic setting. Using some weaker structure than a topos and making size distinctions might be interesting to the extent that it addresses that concern.

**Comment by jonsterling** [comment]
@freebroccolo Cool, I think we largely agree then; because we make no use of the impredicative features of a topos in the ABT paper, I don't think we need to draw attention to it (since nobody will have reason to even be worried about it), whereas in the refinements paper, it may be a good idea to take predicativity seriously and either use these small maps, or the weaker notion that van den Berg has mentioned.

Do you have enough intuition yet about van den Berg's approach that you might be able to summarize it for me? (Or at least point me to something elementary that I could look at?)

**Comment by freebroccolo** [comment]
> Do you have enough intuition yet about van den Berg's approach that you might be able to summarize it for me? (Or at least point me to something elementary that I could look at?)

I think I need to do some more reading before I understand whats going on. That paper I linked doesn't seem too gnarly but I only skimmed it. [This one](http://arxiv.org/pdf/1207.0959v1.pdf) is more recent and sounds like it's intended to give a broader overview. Maybe it would be good to look at that one first.
