### ISSUE TITLE
rearrange paper somewhat

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/syntax-and-semantics-of-abts#40]
At first, the material was elementary enough that it made sense to develop whatever machinery was needed along the way toward ABTs, but now I think that this arrangement is starting to feel a bit unwieldy.

In particular, it seems very strange that we start off describing sorts and valences, and then jump into all this sheaf stuff, only to come back to describing describing operators and arities a few pages later.

I think it might make sense to arrange things in a way that's more like the following (note: the following is just a rearrangement, and doesn't entail the addition of any new material, except for the clarification of a few things that are glossed over):

1. Fix a set of sorts.
2. Define symbols and symbol contexts; actually explain that comma construction, since the unfortunate notation is very confusing to people who haven't seen the literature, I've found. (That is, we should make explicit what the functors in play are, and then say that the notation we use is shorthand for that).
3. Give intuition for co-presheaves on symbol contexts. Motivate the sheaf condition.
4. Briefly explain sheaves, and the atomic site on symbol contexts (also, there's a trivial lemma we need to prove to show that this actually is a Grothendieck site); possibly retain description of sheafification, though I haven't actually needed to use it yet (so we may get rid of it, unless we feel that it helps with the intuition).
5. Digression: explain the relationship between this apparatus and the Schanuel topos (Theorem: as in the Schanuel topos, the sheaf condition for our site is equivalent to preservation of pullbacks). Conjecture: the category of sheaves on this site is equivalent to the limit of `Nom[–]`, where `Nom[s]` is the category of multi-sorted nominal sets under a global sort assignment `s : Atoms -> Sorts`.
6. NOW, resume defining ABTs without interruption.

I think that the above arrangement makes the paper more easily skimmable; I hate when a paper has a bunch of preliminary material interleaved with the "meat" of it, since it makes it really hard to tell what I need to read carefully, or at least pay attention to—it also makes it less clear what the "point" of the paper is. This way, readers who know all about grothendieck sheaves, nominal sets, etc. can basically skip an entire section (or at least, read it only lightly).

**Comment by freebroccolo** [comment]
This sounds pretty good to me. I agree that the structure was starting to feel a bit awkward given how it was evolving. One thing I am a little bit concerned about is how accessible some of this will be but I suppose whether that's really an issue that depends a lot on where it will be submitted.

**Comment by jonsterling** [comment]
@freebroccolo Yeah, I share that concern... I guess I'm not really sure who's the audience for this; I think most PL people and type theorists probably don't care about this stuff...

My hope is that with the proposed arrangement, we can make it easier for people to "skip to" the part that they actually want to see.
