### ISSUE TITLE
address bob's comments

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/syntax-and-semantics-of-abts#42]

**Comment by jonsterling** [comment]
one thing bob wasn't crazy about was the double-struck lambda notation for abstractions; his reason was that the lambda evokes the idea of an exponential, but there's no exponential involved here.

@freebroccolo what do you think?

**Comment by freebroccolo** [comment]
Yeah, I saw that part. I don't feel super strongly about the lambda so if you want to remove it I won't be upset about it but on the other hand I don't find the objection wrt to exponentials to be very persuasive on its own. I think the lambda improves readability a bit and potentially provides some intuition about what's going on there on a cursory reading. Given that we don't really talk about exponentials (aside from the model theory) or present the rules and stuff in adjunctional style, I guess don't really see much room for confusion.

**Comment by jonsterling** [comment]
Yeah, I don't disagree with you. I might try leaving it as is, if only because the lambda notation is easier to parse.
