### ISSUE TITLE
add references

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/syntax-and-semantics-of-abts#5]
- [x] aczel
- [x] harper / pfpl
- [x] fiore
- [x] mahmoud
- [x] pitts
- [x] hamana
- [x] crary / explicit contexts
- [x] mechanization of standard ml
- [x] martens & crary / mechanization of ELF in twelf

who else?

**Comment by freebroccolo** [comment]
Hamana (for metavariables). I think this may be the original reference: http://www.cs.gunma-u.ac.jp/~hamana/Papers/free.pdf

**Comment by jonsterling** [comment]
@freebroccolo OK, I definitely need metavariables, so let's cite Hamana. Thanks for the references!

**Comment by freebroccolo** [comment]
And just for reference I think the earliest explanation of explicit substitution in Fiore style may be http://cs.ioc.ee/~tarmo/papers/merlin03-hosc.pdf (Ghani, Uustalu, Hamana). Essentially it is just another constructor for the tree syntax that acts as the suspended monadic bind (which can be encoded in terms of Lan or Coyoneda or whatever). The concrete implementation at the end uses the polymorphic recursion style but it works perfectly well with Fin, you just end up with a relative monad.

**Comment by jonsterling** [comment]
We should also cite Fiore / Hur, Second Order Equational Logic, which includes a bit more detail on the model theory for multisorted calculi.
